name: OptimizedTNTPlugin
version: 1.0.0
main: com.optimizetnt1.OptimizeTNT1
author: Redblazer23
description: Plugin to optimize TNT explosions
commands:
  optimizedtnt:
    description: Enable or disable optimized TNT explosions
    usage: /optimizedTNT <on/off>
